from enum import Enum

class StatusCode(str, Enum):
    SUCCESS_CODE = 'DB_SUCCESS_001'
    LOGOUT_CODE = 'DB_0002'
    CREATE_USER_CODE = 'DB_1100'
    UPDATE_USER_CODE = 'DB_1101'
    DELETE_USER_CODE = 'DB_1102'
    CREATE_ROLE_CODE = 'DB_1103'
    UPDATE_ROLE_CODE = 'DB_1104'
    DELETE_ROLE_CODE = 'DB_1105'
    CREATE_ENTERPRISE_CODE = 'DB_1106'
    UPDATE_ENTERPRISE_CODE = 'DB_1107'
    DELETE_ENTERPRISE_CODE = 'DB_1108'
    CREATE_TASK_TYPE_CODE = 'DB_1109'
    UPDATE_TASK_TYPE_CODE = 'DB_1110'
    DELETE_TASK_TYPE_CODE = 'DB_1111'
    CREATE_TASK_CODE = 'DB_1112'
    UPDATE_TASK_CODE = 'DB_1113'
    DELETE_TASK_CODE = 'DB_1114'

    def __str__(self):
        return self.value